name: Despliegue a Surge.sh

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Instalar Surge.sh
      run: npm install -g surge

    - name: Desplegar a Surge.sh
      run: surge ./ --domain alinaesther.surge.sh --token ${{ secrets.SURGE_TOKEN }}
      env:
        SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
        